= zgn_opengl

The zgn_opengl interface is exposed as a global object enabling clients to draw
contents of virtual objects using OpenGL-like APIs.

== vertex_attribute_type
`enum`

Please refer to the specification of OpenGL `glVertexAttribPointer` (type param)
for details.

The vertex_attribute_type codes match the macros defined in GL/glew.h

== topology
`enum`

The topology codes match the macros defined in GL/glew.h

== destroy
`request`

Using this request a client can tell the server that it is not going to use the
zgn_opengl object anymore.

Objects created from the zgn_opengl (texture, vertex buffer, etc.) will not be destroyed.

== create_opengl_component
`request`

Ask the compositor to create a new zgn_opengl_component object.

== create_vertex_buffer
`request`

Ask the compositor to create a new zgn_opengl_vertex_buffer object.

== create_shader_program
`request`

Ask the compositor to create a new zgn_shader_program object.

== create_texture
`request`

Ask the compositor to create a new zgn_texture_program object.
