= zgn_opengl_shader_program

This is an interface to create and build shader programs.

A zgn_opengl_shader_program which has not been called
zgn_opengl_shader_program.link is useless. Clients need to call
zgn_opengl_shader_program.link before the zgn_virtual_object.commit
to use the shader programs for the rendering in the commit.

The shader program is immutable, and once zgn_opengl_shader_program.link is
called, client cannot change the contents of the
zgn_opengl_shader_program object.

== error
`enum`

|===
|entry|description

|compilation_error
|failed to compile shaders

|linkage_error
|failed to link program objects

|immutable_error
|clients tried to change the content of shader program which has already been linked.

|invalid_uniform_variable
|clients tried to set uniform variables with invalid vector / matrix size
|===

== destroy
`request`

Destroy a zgn_opengl_shader_program object.

== set_uniform_float_vector
`request`

Specify the value of a uniform variable for the program object.

`size` parameter must be 1, 2, 3 or 4.

== set_uniform_float_matrix
`request`

Specify the value of a uniform variable for the program object.

`col` and `row` parameter must be 2, 3 or 4.

== set_vertex_shader
`request`

Set the contents of vertex shader. The compositor reads and compiles the shader
immediately, and if the compilation fails, the request raises compilation_error.

Clients need to call zgn_opengl_shader_program.link after this request to apply
the changes.

== set_fragment_shader
`request`

Set the contents of fragment shader. The compositor reads and compiles the
shader immediately, and if the compilation fails, the request raises
compilation_error.

Clients need to call zgn_opengl_shader_program.link after this request to apply
the changes.

== link
`request`

This request links the shader programs set to a zgn_opengl_shader_program before
this request. If it fails to link, this request raises linkage_error.

Once a client calls this request, the client must not call set_vertex_shader,
set_fragment_shader and link request.
