= zgn_virtual_object

"Virtual Object" is a concept which represents a unit of interactive 3D object.
Each virtual object has a local coordinate. Clients draw the content of a
virtual object and receive the input event (such as zgn_ray.motion) in the
virtual-object-local space.

A virtual object without a "role" is fairly useless: a compositor does not know
where, when or how to present it. The role is the purpose of a
zgn_virtual_object. Examples of roles are a preview object during drag & drop
action and a cuboid window.

Virtual object can have one role at a time, Initially a zgn_virtual_object does
not have a role. Once a zgn_surface is given a role, it is set permanently for
the whole lifetime of the zgn_virtual_object object. Giving the current role
again in allowed, unless explicitly forbidden by the relevant interface
specification.

Virtual object roles are given by requests in other interfaces. The request
should explicitly mention that the request gives a role to a
zgn_virtual_object. Often, this request also creates new protocol object that
represents the role and add additional functionality or restriction to
zgn_virtual_object, e.g., the way to draw its content. When a client wants to
destroy a zgn_virtual_object, they must destroy this 'role object' before the
zgn_virtual_object.

The protocol to draw the content of a virtual object will be defined by other
interfaces, e.g. zgn_opengl.

Destroying the role object does not remove the role from the
zgn_virtual_object, but it may stop the zgn_virtual_object from
"playing the role".

== destroy
`request`

Delete the virtual object and invalidates its object ID.

== commit
`request`

commit request は Virtual object の state (見た目など) に対する一連の変更を適用するのに用います。
Virtual object の state は double-buffer となっており、このrequest によって commit されるまでは適応されません。
Virtual object の state は外部の Interface によって定義され、外部の Interface の request によって変更されます。
外部の Interface は Virtual Object の state を変更する request を定義する場合、
その旨を protocol の中で明記する必要があります。

== frame
`request`

Request a notification when it is a good time to start preparing a new
virtual object state related to its appearance, by creating a frame callback.
This is useful for throttling redrawing operations, and driving animations.

When a client is animating on a zgn_virtual_object, it can use the 'frame'
request to get notified when it is a good time to commit the next object state.
If the client commits an update earlier than that, it is likely that some
update will not make it to the display, and the client is wasting resources
by calculating the state too often.

The frame request will take effect on the next zgn_virtual_object.commit.
The notification will only be posted for one frame unless
requested again. The server should give some time for the client
to calculate and commit the new state after sending the frame callback
events to let it hit the next output refresh.

A server should avoid signaling the frame callbacks if the
object is not visible in any way, e.g. the object is off-screen,
or completely obscured.

The object returned by this request will be destroyed by the
compositor after the callback is fired and as such the client must not
attempt to use it after that point.

The callback_data passed in the callback is the current time, in
milliseconds, with an undefined base
